trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr: none

resources:
  repositories:
  - repository: PSRepositoryReleaseManager
    type: github
    name: theohbrothers/PSRepositoryReleaseManager
    endpoint: joeltimothyoh
    ref: refs/heads/dev

stages:
- stage: Build_Release
  displayName: Build, Release
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
    - checkout: self
      submodules: recursive
    - bash: echo hello
    - template: templates/azure-pipelines/run-release.yml@PSRepositoryReleaseManager
