name: ci-master-pr

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  generate-and-release:
    runs-on: ubuntu-latest
    container:
      image: theohbrothers/docker-powershell:7.2-ubuntu-22.04-git
    steps:
    - uses: actions/checkout@v1
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Ignore git permissions
      run: |
        git config --global --add safe.directory "$( pwd )"
    - name: Generate release notes
      run: |
        # Clone project
        git clone https://github.com/theohbrothers/PSRepositoryReleaseManager.git --recurse-submodules --branch 'fix/release-fix-default-variable-values-for-when-env-release_draft-and-env-release_prerelease-are-null-or-undefined' PSRepositoryReleaseManager

        # Process applicable environment variables
        export PROJECT_DIRECTORY="$(git rev-parse --show-toplevel)"
        export RELEASE_TAG_REF=$( echo "$GITHUB_REF" | sed -rn 's/^refs\/tags\/(.*)/\1/p' )

        # echo "GITHUB_REF: $GITHUB_REF"
        # echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        # echo "RELEASE_TAG_REF: $RELEASE_TAG_REF"

        # Generate (Generates release notes)
        pwsh -c '$VerbosePreference = "Continue"; ./PSRepositoryReleaseManager/src/scripts/ci/Invoke-Generate.ps1'
        cat PSRepositoryReleaseManager/.release-notes.md
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-notes
        path: PSRepositoryReleaseManager/.release-notes.md
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        # Process applicable environment variables
        export PROJECT_DIRECTORY="$(git rev-parse --show-toplevel)"
        export RELEASE_TAG_REF=$( echo "$GITHUB_REF" | sed -rn 's/^refs\/tags\/(.*)/\1/p' )
        export RELEASE_NAMESPACE="$GITHUB_REPOSITORY_OWNER"
        export RELEASE_REPOSITORY=$(basename "$(git rev-parse --show-toplevel)")

        # echo "GITHUB_REF: $GITHUB_REF"
        # echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        # echo "RELEASE_TAG_REF: $RELEASE_TAG_REF"

        # Release (Creates GitHub release)
        # pwsh -c 'gci env:*'
        pwsh -c '$VerbosePreference = "Continue"; ./PSRepositoryReleaseManager/src/scripts/ci/Invoke-Release.ps1'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
